name: stxit_v1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - blast
  - iqtree
  - fasttree
  - entrez-direct
  - ncbi-datasets-cli
  - trnascan-se
  - pip
  - pip:
      - biopython
      - pandas
      - openpyxl
      - matplotlib
